name: DartStream CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get
        working-directory: projects/tesseract

      - name: Analyze project
        run: dart analyze
        working-directory: projects/tesseract

      - name: Run tests
        run: dart test
        working-directory: projects/tesseract

      - name: Install DartStream CLI
        run: dart pub global activate ds_dartstream

      - name: Validate project
        run: dartstream validate --project tesseract
        env:
          DARTSTREAM_TOKEN: ${{ secrets.DARTSTREAM_TOKEN }}

      - name: Generate & deploy
        run: dartstream configure --name tesseract --skip-examples
        env:
          DARTSTREAM_TOKEN: ${{ secrets.DARTSTREAM_TOKEN }}
